BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        text: 'Clear'
    Button:
        text: 'two'
    Button:
        text: 'Greet'
        on_press: app.handle_greet()
    Label:
        text: 'Enter your name'
        color: (1, 1, 0, 1)

#        """BoxLayout:
#    orientation: 'vertical'
#    Button:
#        text: "Press me"
#        on_press: app.handle_pressed()
#    Label:
#        id: my_label
#        text: "Hello world"
#        font_size: 42"