BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        text: 'Clear'
        on_press: app.handle_clear()
    Button:
        text: 'two'
        TextInput:
            id: input_name
            text: ''
    Button:
        text: 'Greet'
        on_press: app.handle_greet()
        id: output_label
    Label:
        text: 'Enter your name'
        color: (1, 1, 0, 1)

